const IS_APP_LOADING: string = 'app/IS_APP_LOADING';
const CREATE_REQUEST_FORM: string = 'app/CREATE_REQUEST_FORM';
const SHOW_CURRENT_LOCATION = 'app/SHOW_CURRENT_LOCATION';

export { IS_APP_LOADING, CREATE_REQUEST_FORM, SHOW_CURRENT_LOCATION };
