const IS_APP_LOADING: string = 'app/IS_APP_LOADING';
const CREATE_REQUEST_FORM: string = 'app/CREATE_REQUEST_FORM';
const UPDATE_USER_DATA = 'app/UPDATE_USER_DATA';
const UPDATE_REQUESTS_MAP = 'app/UPDATE_REQUEST_MAP';
const UPDATE_VOLUNTEERS_MAP = 'app/UPDATE_VOLUNTEERS_MAP';
const UPDATE_REQUEST_ADDRESS = 'app/UPDATE_REQUEST_ADDRESS';
const UPDATE_NOTIFICATIONS = 'app/UPDATE_NOTIFICATIONS';

export {
  IS_APP_LOADING,
  CREATE_REQUEST_FORM,
  UPDATE_USER_DATA,
  UPDATE_REQUESTS_MAP,
  UPDATE_VOLUNTEERS_MAP,
  UPDATE_REQUEST_ADDRESS,
  UPDATE_NOTIFICATIONS,
};
