const IS_APP_LOADING: string = 'app/IS_APP_LOADING';
const CREATE_REQUEST_FORM: string = 'app/CREATE_REQUEST_FORM';
const SHOW_CURRENT_LOCATION = 'app/SHOW_CURRENT_LOCATION';
const UPDATE_USER_DATA = 'app/UPDATE_USER_DATA';
const UPDATE_REQUEST_LIST = 'app/UPDATE_REQUEST_LIST';

export {
  IS_APP_LOADING,
  CREATE_REQUEST_FORM,
  SHOW_CURRENT_LOCATION,
  UPDATE_USER_DATA,
  UPDATE_REQUEST_LIST,
};
