const UPDATE_STATUS_FILTER: string = 'requestFilter/UPDATE_STATUS_FILTER';
const UPDATE_NAME_FILTER: string = 'requestFilter/UPDATE_CATEGORY_FILTER';
const UPDATE_CATEGORY_FILTER: string = 'requestFilter/UPDATE_CATEGORY_FILTER';

export { UPDATE_STATUS_FILTER, UPDATE_NAME_FILTER, UPDATE_CATEGORY_FILTER };
